### ISSUE TITLE
Wong login discord popup size (qr-code login)

### ISSUE THREAD

**Issue by JulesdeCube** [EpiLink/EpiLink#250]
## Problem description
Durring the discord login steps the popup windows is to small and discord didn't show the qr-code login.

## Steps to reproduce
1. go to epilink login page
2. click on the `discord login` button

## Actual behavior
![image](https://user-images.githubusercontent.com/41579596/102010454-62d00a00-3d3e-11eb-8a2d-e62c6c56eb1e.png)

## Expected behavior
![image](https://user-images.githubusercontent.com/41579596/102010537-f4d81280-3d3e-11eb-8f52-34a4a0296e8f.png)

**Comment by utybo** [comment]
The OAuth2 login does not support QR code login. There isn't much we can do about it as this is probably a security measure from Discord.

QR codes allow you to login to their own platform, but OAuth2 is all about giving other people access to sensitive information with permission. Allowing login via QR codes would be a significant security risk.

Marking this as won't fix since we can't do anything about this.

**Comment by utybo** [comment]
I'm an idiot and I can't read, I thought you were saying that login was just entirely impossible 🤦 

@Litarvan up to you

**Comment by Litarvan** [comment]
Fixed in 0.6.2, deployed in production
